name: Fullstack CI/CD

on:
  push:
    paths:
      - 'api/**'
      - 'webapp/**'
      - 'cloud/docker-compose.yml'
  pull_request:
    paths:
      - 'api/**'
      - 'webapp/**'
      - 'cloud/docker-compose.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for API Tests
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and test API
        working-directory: api
        run: |
          npm ci
          npm test

      - name: Install and test Frontend
        working-directory: webapp
        run: |
          npm ci
          npm run test -- --watchAll=false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push API image
        run: |
          docker build -t orisuniyanu/ecommerce-api ./api
          docker push orisuniyanu/ecommerce-api

      - name: Build and push Webapp image
        run: |
          docker build -t orisuniyanu/ecommerce-webapp ./webapp
          docker push orisuniyanu/ecommerce-webapp

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            cd ~
            if [ ! -d "cloud" ]; then
              git clone https://github.com/Orisuniyanu/ecommerce-platform.git cloud
            else
              cd cloud
              git pull origin main
            fi
            cd cloud
            docker pull orisuniyanu/ecommerce-api
            docker pull orisuniyanu/ecommerce-webapp
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml up -d
